const BookingData = [
    {
        id: "AB123456",
        name: "Thomas Shelby",
        vendorName: "Robert Oppenheimer",
        street: "Jane Street",
        city: "London",
        state: "London",
        pin: "124632",
        country: "United Kingdom",
        project: "Atomos",
        service: "Architect",
        subService: "Video Call",
        date: "23-07-2023",
        mobile: 7689076547,
        time: "00:30 Hrs",
        amount: 3000,
    },
    {
        id: "AB123456",
        name: "Thomas Shelby",
        vendorName: "Robert Oppenheimer",
        street: "Jane Street",
        city: "London",
        state: "London",
        pin: "124632",
        country: "United Kingdom",
        project: "Atomos",
        service: "Architect",
        subService: "Video Call",
        date: "23-07-2023",
        mobile: 7689076547,
        time: "00:30 Hrs",
        amount: 3000,
    },
    {
        id: "AB123456",
        name: "Thomas Shelby",
        vendorName: "Robert Oppenheimer",
        street: "Jane Street",
        city: "London",
        state: "London",
        pin: "124632",
        country: "United Kingdom",
        project: "Atomos",
        service: "Architect",
        subService: "Video Call",
        date: "23-07-2023",
        mobile: 7689076547,
        time: "00:30 Hrs",
        amount: 3000,
    },
    {
        id: "AB123456",
        name: "Thomas Shelby",
        vendorName: "Robert Oppenheimer",
        street: "Jane Street",
        city: "London",
        state: "London",
        pin: "124632",
        country: "United Kingdom",
        project: "Atomos",
        service: "Architect",
        subService: "Video Call",
        date: "23-07-2023",
        mobile: 7689076547,
        time: "00:30 Hrs",
        amount: 3000,
    },
    {
        id: "AB123456",
        name: "Thomas Shelby",
        vendorName: "Robert Oppenheimer",
        street: "Jane Street",
        city: "London",
        state: "London",
        pin: "124632",
        country: "United Kingdom",
        project: "Atomos",
        service: "Architect",
        subService: "Video Call",
        date: "23-07-2023",
        mobile: 7689076547,
        time: "00:30 Hrs",
        amount: 3000,
    },
    {
        id: "AB123456",
        name: "Thomas Shelby",
        vendorName: "Robert Oppenheimer",
        street: "Jane Street",
        city: "London",
        state: "London",
        pin: "124632",
        country: "United Kingdom",
        project: "Atomos",
        service: "Architect",
        subService: "Video Call",
        date: "23-07-2023",
        mobile: 7689076547,
        time: "00:30 Hrs",
        amount: 3000,
    },
    {
        id: "AB123456",
        name: "Thomas Shelby",
        vendorName: "Robert Oppenheimer",
        street: "Jane Street",
        city: "London",
        state: "London",
        pin: "124632",
        country: "United Kingdom",
        project: "Atomos",
        service: "Architect",
        subService: "Video Call",
        date: "23-07-2023",
        mobile: 7689076547,
        time: "00:30 Hrs",
        amount: 3000,
    },
    {
        id: "AB123456",
        name: "Thomas Shelby",
        vendorName: "Robert Oppenheimer",
        street: "Jane Street",
        city: "London",
        state: "London",
        pin: "124632",
        country: "United Kingdom",
        project: "Atomos",
        service: "Architect",
        subService: "Video Call",
        date: "23-07-2023",
        mobile: 7689076547,
        time: "00:30 Hrs",
        amount: 3000,
    },
    {
        id: "AB123456",
        name: "Thomas Shelby",
        vendorName: "Robert Oppenheimer",
        street: "Jane Street",
        city: "London",
        state: "London",
        pin: "124632",
        country: "United Kingdom",
        project: "Atomos",
        service: "Architect",
        subService: "Video Call",
        date: "23-07-2023",
        mobile: 7689076547,
        time: "00:30 Hrs",
        amount: 3000,
    },
    {
        id: "AB123456",
        name: "Thomas Shelby",
        vendorName: "Robert Oppenheimer",
        street: "Jane Street",
        city: "London",
        state: "London",
        pin: "124632",
        country: "United Kingdom",
        project: "Atomos",
        service: "Architect",
        subService: "Video Call",
        date: "23-07-2023",
        mobile: 7689076547,
        time: "00:30 Hrs",
        amount: 3000,
    },
    {
        id: "AB123456",
        name: "Thomas Shelby",
        vendorName: "Robert Oppenheimer",
        street: "Jane Street",
        city: "London",
        state: "London",
        pin: "124632",
        country: "United Kingdom",
        project: "Atomos",
        service: "Architect",
        subService: "Video Call",
        date: "23-07-2023",
        mobile: 7689076547,
        time: "00:30 Hrs",
        amount: 3000,
    },
    {
        id: "AB123456",
        name: "Thomas Shelby",
        vendorName: "Robert Oppenheimer",
        street: "Jane Street",
        city: "London",
        state: "London",
        pin: "124632",
        country: "United Kingdom",
        project: "Atomos",
        service: "Architect",
        subService: "Video Call",
        date: "23-07-2023",
        mobile: 7689076547,
        time: "00:30 Hrs",
        amount: 3000,
    },
    {
        id: "AB123456",
        name: "Thomas Shelby",
        vendorName: "Robert Oppenheimer",
        street: "Jane Street",
        city: "London",
        state: "London",
        pin: "124632",
        country: "United Kingdom",
        project: "Atomos",
        service: "Architect",
        subService: "Video Call",
        date: "23-07-2023",
        mobile: 7689076547,
        time: "00:30 Hrs",
        amount: 3000,
    },
    {
        id: "AB123456",
        name: "Thomas Shelby",
        vendorName: "Robert Oppenheimer",
        street: "Jane Street",
        city: "London",
        state: "London",
        pin: "124632",
        country: "United Kingdom",
        project: "Atomos",
        service: "Architect",
        subService: "Video Call",
        date: "23-07-2023",
        mobile: 7689076547,
        time: "00:30 Hrs",
        amount: 3000,
    },
];

export default BookingData;