const DataList = [
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        transactionId: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Credited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        transactionId: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Debited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        transactionId: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Credited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        transactionId: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Debited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        transactionId: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Debited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        transactionId: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Credited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        transactionId: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Debited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        transactionId: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Debited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        transactionId: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Debited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        transactionId: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Credited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        transactionId: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Credited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        itransactionIdd: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Debited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        transactionId: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Debited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        transactionId: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Credited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        itransactionIdd: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Credited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        transactionId: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Credited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        transactionId: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Credited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        transactionId: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Credited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        transactionId: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Credited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        transactionId: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Credited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        transactionId: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Credited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        transactionId: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Credited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        transactionId: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Credited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        transactionId: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Credited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        transactionId: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Credited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        transactionId: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Credited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        transactionId: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Credited",
    },
    {
        name: "John Wick",
        vendorName: "Hailey Kukou",
        itransactionIdd: "AB0953674562",
        service: "Architect",
        subService: "Video Call",
        amount: "₹ 1,876",
        date: "23-07-2023",
        status: "Credited",
    },
];

export default DataList;