const DataList = [
    {
        icon: "/Images/ServiceIcon1.png",
        service: "Architect",
        rating: 4,
        image: "",
        description: "",
    },
    {
        icon: "/Images/ServiceIcon2.png",
        service: "Civil Engineer",
        rating: 4,
        image: "",
        description: "",
    },
    {
        icon: "/Images/ServiceIcon3.png",
        service: "Civil Supervisor",
        rating: 4,
        image: "",
        description: "",
    },
    {
        icon: "/Images/ServiceIcon4.png",
        service: "Vast Consultant",
        rating: 4,
        image: "",
        description: "",
    },
    {
        icon: "/Images/ServiceIcon5.png",
        service: "Interior Designer",
        rating: 4,
        image: "",
        description: "",
    },
    {
        icon: "/Images/ServiceIcon6.png",
        service: "Legal Consultant",
        rating: 4,
        image: "",
        description: "",
    },
    {
        icon: "/Images/ServiceIcon7.png",
        service: "Account Consultant",
        rating: 4,
        image: "",
        description: "",
    },
    {
        icon: "/Images/ServiceIcon8.png",
        service: "General Consultant",
        rating: 4,
        image: "",
        description: "",
    },
    {
        icon: "/Images/ServiceIcon1.png",
        service: "Architect",
        rating: 4,
        image: "",
        description: "",
    },
    {
        icon: "/Images/ServiceIcon2.png",
        service: "Civil Engineer",
        rating: 4,
        image: "",
        description: "",
    },
    {
        icon: "/Images/ServiceIcon3.png",
        service: "Vatu Consultant",
        rating: 4,
        image: "",
        description: "",
    },
    {
        icon: "/Images/ServiceIcon4.png",
        service: "General Consultant",
        rating: 4,
        image: "",
        description: "",
    },
    {
        icon: "/Images/ServiceIcon5.png",
        service: "Account Consultant",
        rating: 4,
        image: "",
        description: "",
    },
    {
        icon: "/Images/ServiceIcon6.png",
        service: "Legal Consultant",
        rating: 4,
        image: "",
        description: "",
    },
];

export default DataList;