const DataList = [
    {
        name: "Edgar Jones",
        email: "jonesedgar@gmail.com",
        mobile: "8790657689",
        assignedRole: "Quality Management",
        usersAssigned: "10",
        city: "Delhi",
    },
    {
        name: "James Holts",
        email: "james@gmail.com",
        mobile: "732357689",
        assignedRole: "Manager",
        usersAssigned: "9",
        city: "Mumbai",
    },
    {
        name: "Hellen Moriarty",
        email: "hellen@gmail.com",
        mobile: "743243276",
        assignedRole: "Query Management",
        usersAssigned: "18",
        city: "Mumbai",
    },
    {
        name: "Pawan Mishra",
        email: "pawan@gmail.com",
        mobile: "8790657689",
        assignedRole: "Operations Management",
        usersAssigned: "10",
        city: "Delhi",
    },
    {
        name: "Aditya Rikhari",
        email: "rikhari@gmail.com",
        mobile: "8790657689",
        assignedRole: "Sales Management",
        usersAssigned: "14",
        city: "Pune",
    },
    {
        name: "Jyotsna Sharma",
        email: "jyotsna@gmail.com",
        mobile: "8790657689",
        assignedRole: "Finance Management",
        usersAssigned: "6",
        city: "Bangalore",
    },
    {
        name: "Edgar Jones",
        email: "jonesedgar@gmail.com",
        mobile: "8790657689",
        assignedRole: "Quality Management",
        usersAssigned: "10",
        city: "Hyderabad",
    },
    {
        name: "Edgar Jones",
        email: "jonesedgar@gmail.com",
        mobile: "8790657689",
        assignedRole: "Quality Management",
        usersAssigned: "10",
        city: "Chennai",
    },
    {
        name: "Edgar Jones",
        email: "jonesedgar@gmail.com",
        mobile: "8790657689",
        assignedRole: "Quality Management",
        usersAssigned: "10",
        city: "Pune",
    },
    {
        name: "Edgar Jones",
        email: "jonesedgar@gmail.com",
        mobile: "8790657689",
        assignedRole: "Quality Management",
        usersAssigned: "10",
        city: "Delhi",
    },
    {
        name: "Edgar Jones",
        email: "jonesedgar@gmail.com",
        mobile: "8790657689",
        assignedRole: "Quality Management",
        usersAssigned: "10",
        city: "Mumbai",
    },
    {
        name: "Edgar Jones",
        email: "jonesedgar@gmail.com",
        mobile: "8790657689",
        assignedRole: "Quality Management",
        usersAssigned: "10",
        city: "Bangalore",
    },
    {
        name: "Edgar Jones",
        email: "jonesedgar@gmail.com",
        mobile: "8790657689",
        assignedRole: "Quality Management",
        usersAssigned: "10",
        city: "Delhi",
    },
    {
        name: "Edgar Jones",
        email: "jonesedgar@gmail.com",
        mobile: "8790657689",
        assignedRole: "Quality Management",
        usersAssigned: "10",
        city: "Delhi",
    },
    {
        name: "Edgar Jones",
        email: "jonesedgar@gmail.com",
        mobile: "8790657689",
        assignedRole: "Quality Management",
        usersAssigned: "10",
        city: "Delhi",
    },
    {
        name: "Edgar Jones",
        email: "jonesedgar@gmail.com",
        mobile: "8790657689",
        assignedRole: "Quality Management",
        usersAssigned: "10",
        city: "Delhi",
    },
];

export default DataList;